# Generated by Django 5.0.2 on 2024-03-04 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=800)),
                ('work_date', models.DateField()),
                ('work_time', models.IntegerField(default=0)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_CRUD.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_CRUD.user')),
            ],
        ),
    ]
