# Generated by Django 5.0.2 on 2024-03-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_CRUD', '0002_userwithtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithtask',
            name='work_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='userwithtask',
            name='work_time',
            field=models.IntegerField(null=True),
        ),
    ]
