# Generated by Django 5.0.2 on 2024-03-06 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_CRUD', '0003_alter_userwithtask_work_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithtask',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='db_CRUD.project'),
            preserve_default=False,
        ),
    ]
