# Generated by Django 5.0.2 on 2024-03-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_CRUD', '0004_userwithtask_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
    ]
