# Generated by Django 5.0.2 on 2024-03-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_CRUD', '0005_rename_login_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='login',
        ),
    ]
