# Generated by Django 5.0.2 on 2024-02-27 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=800)),
                ('last_name', models.CharField(max_length=800)),
                ('father_name', models.CharField(max_length=800)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('job_title_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.jobtitle')),
            ],
        ),
        migrations.AlterField(
            model_name='workontask',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first.user'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
